### ISSUE TITLE
Html.ActionLink urls incorrect

### ISSUE THREAD

**Issue by vincelee888** [atas/lowercase-dashed-route#1] opened 2013-08-16 07:31 UTC
Hi,

There seems to be an issue with Html.ActionLink not rendering the link correctly.

On my page, /bespoke-documents/ I have a View action to view each document. However, the link reads as: /bespokedocuments/view/{docid}, not /bespoke-documents/view/{docid}. 

The link still works, but I would hope for consistency

Cheers

Vince

**Comment by atas** [comment] 2013-08-16 08:14
Hi Vince,

Is there any attribute/annotation assigned to the Controller or is the controller not in CamelCase i.e. "BespokeDocuments"?

Best,
Ata

**Comment by vincelee888** [comment] 2013-08-16 10:52
Hi Ata, thanks for getting back to me

The Controller is: BespokeDocuments
The Action in question is View

When I do @Html.ActionLink("View File", "View", new { id = document.Id } in my razor page, it goes to:

/bespokedocuments/view/id=123

@Html.ActionLink("Documents", "Index", "BespokeDocuments" works fine

**Comment by atas** [comment] 2013-08-20 12:26
Hey there Vince! Thanks for letting me know about this issue. Can you please update the package through NuGet, compile the project and let me know if the issue is gone? I've found the reason, tested and it was gone for me.

Btw, the issue was only happening when the controller was not specified explicitly i.e. when using the current controller which loaded that view page.

**Closed as completed** 2013-08-23 21:26 UTC
Labels: bug
